# Generated by Django 5.2.5 on 2025-08-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=225)),
                ('name', models.CharField(max_length=225)),
                ('password', models.CharField(max_length=225)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
